name: jimbob88-cran-parser
base: core20
version: '0.1'
summary: A tool for creating install scripts from CRAN snapshots
description: |
  A tool designed for making install scripts from CRAN snapshots. 
  This lets you easily and simply install packages that are no longer 
  compiled for new versions of R (like sensR).

grade: devel
confinement: devmode

architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  cran-parser:
    command: bin/cran_parser
    plugs: []


parts:
  cran-parser:
    plugin: python
    requirements: [./requirements.txt]
    source: .